[server]
port = ":9081"
max_process = 2
version = "1.0.0"
name = "spider_strategy"
data_path = "/opt/www/monitor_coin.deploy/data"

[log]
log_path = "/opt/logs/monitor_coin/"
keep_hours = 72

[redis]
addr = "127.0.0.1:6379"
password = ""

[mysql]
dsn = "root:password@tcp(localhost:3306)/mb_coin?charset=utf8&timeout=2000ms"
retry = 2
pool_max_idle_conn = 2
pool_max_open_conn = 20

[binance]
host = ["https://api.binance.com"]
timeout_sec = 3
sign_key = ""

[mexc]
host = ["https://api.mexc.com"]
timeout_sec = 3
sign_key = ""

[teleGram]
host = ["https://api.telegram.org"]
timeout_sec = 10
sign_key = ""

[bitget]
host = ["https://api.bitget.com"]
timeout_sec = 3
sign_key = ""

[kucoin]
host = ["https://api.kucoin.com"]
timeout_sec = 3
sign_key = ""

[gateio]
host = ["https://api.gateio.ws"]
timeout_sec = 3
sign_key = ""

[coinbase]
host = ["https://api.exchange.coinbase.com"]
timeout_sec = 3
sign_key = ""

[bitfinex]
host = ["https://api-pub.bitfinex.com"]
timeout_sec = 3
sign_key = ""

[bitstamp]
host = ["https://www.bitstamp.net"]
timeout_sec = 3
sign_key = ""